version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  features:
    build: .  # Собираем из корневой директории
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python features.py
    networks:
      - app-network
    volumes:
      - .:/app  # Монтируем всю директорию проекта

  metric:
    build: .  # Собираем из корневой директории
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python metric.py
    networks:
      - app-network
    volumes:
      - .:/app  # Монтируем всю директорию проекта
      - ./logs:/app/logs  # Отдельно монтируем папку logs

  plot:
    build: .  # Собираем из корневой директории
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python plot.py
    networks:
      - app-network
    volumes:
      - .:/app  # Монтируем всю директорию проекта
      - ./logs:/app/logs  # Отдельно монтируем папку logs

networks:
  app-network:
